### ISSUE TITLE
stable diffusion 2.1의 딜레이 문제

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/ai#2]
## 문제
- 오픈저니나 스테이블 디퓨전 1.4는 3초 걸리지만 스테이블 디퓨전 2.1은 13초 걸림(1024*1024)
- 앞의 둘이 768*768로 밝혀짐

**Comment by evileyemovic** [comment]
스테이블 디퓨전 1024x1024 9초걸림.
