### ISSUE TITLE
특성 키워드 정하기 / 실험용 내용 키워드 정하기

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/ai#3]
## 특성 키워드(가제) 정하기
- 그림의 스타일을 결정하는 키워드 입니다.
- 우선은 내용 키워드보다 항상 앞에 있는 것으로 하면 좋을 것 같아요.
- 모델 실험에서 사용할 특성 키워드를 약 4개 정도 골라주시면 좋을 것 같습니다.

## 실험용 내용 키워드(가제) 정하기
- 실험에서 사용할 내용 키워드를 정해주세요(내용 2가지 정도?).
- 해당 내용 키워드의 문장 버젼도 정해주세요.

**Comment by evileyemovic** [comment]
특성 키워드 : portrait, pencil drawing, crayons drawing, realistic

실험 키워드 : 1) 단어형 : birthday, party, friends
                      2) 문장형 : I had a birthday party with my friends today.
