### ISSUE TITLE
openjourney 테스트

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/ai#5]
## TODO
- #3 의 키워드를 활용해 모델 테스트하기
- 테스트에서 생성된 사진 크기, 소요 시간, 사용 키워드, 생성된 결과물 등을 댓글로 남겨주세요.

**Comment by evileyemovic** [comment]
**openjourney 테스트 결과**
특징 : 768x768 기준 13초, 512x512 기준 4초
          1024x1024를 테스트 해봤으나 메모리 부족 현상 나옴. 
(12.69 GiB reserved in total by PyTorch 라는 경고문이 나오는데, 비정상적인 상황이라고 인식됨)
          사람 얼굴은 알고리즘 상에 일부러 찌그러뜨리는 것 같음.(사람 얼굴은 최대한 안나오게 단어, 문장 넣기)
          crayons drawing, pencil drawing은 다른 단어 싹 무시하는 현상이 빈번히 보임.
          특성 키워드는 앞에 넣나 뒤에 넣나 비슷한 결과를 보임.

결과 : 
![bpf-oj-s](https://user-images.githubusercontent.com/19823171/229267982-04d8cb0a-dcc6-4443-baa5-790db41f82ec.png)
prompt : I had a birthday party with my friends today.
![cbpf-oj1](https://user-images.githubusercontent.com/19823171/229267994-68a20452-bdc9-4417-a4ef-408f41143db1.png)
![cbpf-oj2](https://user-images.githubusercontent.com/19823171/229268006-642d9483-e3ee-4f15-8efa-268268449050.png)
prompt : birthday, party, friends, crayon drawing
![pbpf-oj](https://user-images.githubusercontent.com/19823171/229268021-ba4ab402-b2e1-4f79-8888-9d8adabe30db.png)
prompt : birthday, party, friends, portrait
![pdbpf-oj2](https://user-images.githubusercontent.com/19823171/229268038-1412664c-0014-47a8-a61e-e6dc1ebc9223.png)
prompt : birthday, party, friends, pencil drawing
![rbpf-oj](https://user-images.githubusercontent.com/19823171/229268049-1bd77862-15df-4303-be5c-50ada6d1180e.png)
prompt : birthday, party, friends, realistic
