### ISSUE TITLE
OrangeMixs 테스트

### ISSUE THREAD

**Issue by bluejoyq** [GrimUriCapstone/ai#6]
## TODO
- #3 의 키워드를 활용해 모델 테스트하기
- 테스트에서 생성된 사진 크기, 소요 시간, 사용 키워드, 생성된 결과물 등을 댓글로 남겨주세요.

**Comment by evileyemovic** [comment]
**issue** **orangemix diffusers로 서버에서 받는 것을 지원 안 하는 것으로 보임.**
counterfeit로 진행하였음.
Counterfeit-V2.5 테스트 결과
특징 : 768x768 기준 13초, 512x512 기준 4초
          1024x1024를 테스트 해봤으나 메모리 부족 현상 나옴.
(12.69 GiB reserved in total by PyTorch 라는 경고문이 나오는데, 비정상적인 상황이라고 인식됨)
          **애니풍 모델임**
          애니풍 모델이라 특성 키워드는 무시해버리는 것 같음.

결과 :
![bpf-cf-s](https://user-images.githubusercontent.com/19823171/229268274-fef83dd2-2ac5-4a3d-a965-d30ca557398d.png)
prompt : I had a birthday party with my friends today.
![cbpf-cf](https://user-images.githubusercontent.com/19823171/229268279-3e846f9e-ec8e-4c8a-8d36-773d9a5e1632.png)
prompt : birthday, party, friends, crayon drawing
![pbpf-cf](https://user-images.githubusercontent.com/19823171/229268287-f1fb0a6f-6ac2-47a1-9b37-3b40418c0686.png)
prompt : birthday, party, friends, portrait
![pdbpf-cf](https://user-images.githubusercontent.com/19823171/229268301-202eaf44-44d5-4004-8821-74f13e6b6cbb.png)
prompt : birthday, party, friends, pencil drawing
